### ISSUE TITLE
Cannot open source file `asio.hpp`

### ISSUE THREAD

**Issue by WillNilges** [LucidVR/opengloves-ui#21]
Seems like I'm missing some deps to build this project. I suspect this is related to #20 .

**Comment by danwillm** [comment]
You might have forgotten to clone submodules - asio is included as a submodule, so to clone you would need to do add `--recurse-submodules` to `git clone`

**Comment by WillNilges** [comment]
Aha, that was totally the issue. Mind if I make a PR to add a reminder to the build instructions?

**Comment by danwillm** [comment]
no problem! feel free to make a PR.
