### ISSUE TITLE
Incorrect Description for Servo Calibration

### ISSUE THREAD

**Issue by WillNilges** [LucidVR/opengloves-ui#27]
![image](https://user-images.githubusercontent.com/42927786/219076150-a5bca09c-7854-4031-9bc5-f7af74ba8c87.png)

"Retracting servos fully..." and "retracting them fully..." I'm pretty sure one of those sentences should have "extending" in them, but I dunno which one.

**Comment by WillNilges** [comment]
https://www.youtube.com/watch?v=2yF-SJcg3zQ&t=855s

Seems like FULLY EXTENDED should be "can't close hand" and FULLY RECTRACTED should be "hand has complete freedom of motion"

**Comment by danwillm** [comment]
yep, gonna fix that now, thanks for spotting it!
